### ISSUE TITLE
where can i find "VGG_ILSVRC_19_layers.pytorch"

### ISSUE THREAD

**Issue by Zerahhah** [HenryJia/pytorch-deep-painterly-harmonization#1]

**Comment by HenryJia** [comment]
Haven't added that file in yet. It's essentially the caffe model VGG19 model, which I converted to PyTorch. It seems the first pass doesn't work if you use the original PyTorch TorchVision models. I'm probably not going to continue to develop this anymore since the second pass is proving to be painfully difficult

**Comment by Zerahhah** [comment]
@HenryJia ok, i get it. and i'm very appreciate for your reply.
